export const SKILL_ICONS: Record<string, string> = {
  "Art": "color-palette-outline",
  "Painting": "brush-outline",
  "Photography": "camera-outline",
  "Videography": "videocam-outline",
  "Acting": "film-outline",
  "Singing": "mic-outline",
  "Govt Exam Prep": "book-outline",
  "Short Films": "film-outline",
  "Content Creation": "create-outline",
  "Music": "musical-notes-outline",
  "Dancing": "body-outline",
  "Writing": "pencil-outline",
  "Sketching": "brush-outline",
  "Cooking & Baking": "restaurant-outline",
  "Travel": "airplane-outline",
  "Fashion & Styling": "shirt-outline",
  "Podcasting": "mic-circle-outline",
  "Gardening": "leaf-outline",
  "Pets & Animals": "paw-outline",
  "Filmmaking": "videocam-outline",
  "Music Production": "headset-outline",
  "Skincare & Beauty": "sparkles-outline",
  "Poetry": "quill-outline",
  "Calligraphy": "create-outline",
  "Theatre": "megaphone-outline",
  "DJing": "musical-note-outline",
  "Instrument Playing": "musical-notes-outline",
  "Free Fire": "game-controller-outline",
  "BGMI": "game-controller-outline",
  "Chess": "grid-outline",
  "Valorant": "game-controller-outline",
  "PC/Console Gaming": "game-controller-outline",
  "Board Games": "grid-outline",
  "Puzzles & Trivia": "extension-puzzle-outline",
  "Anime & Manga": "sparkles-outline",
  "Stand-up Comedy": "happy-outline",

  // ── Sports & Fitness ──
  "Gym & Weight Training": "barbell-outline",
  "Yoga": "body-outline",
  "Running": "walk-outline",
  "Cycling": "bicycle-outline",
  "Swimming": "water-outline",
  "Boxing": "fitness-outline",
  "Powerlifting": "barbell-outline",
  "Bodybuilding": "body-outline",
  "Football": "football-outline",
  "Cricket": "baseball-outline",
  "Basketball": "basketball-outline",
  "Tennis": "tennisball-outline",
  "Kabaddi": "people-outline",
  "Athletics": "timer-outline",
  "Badminton": "tennisball-outline",
  "Volleyball": "football-outline",
  "Table Tennis": "tennisball-outline",
  "Martial Arts": "fitness-outline",
  "Calisthenics": "body-outline",
  "Archery": "navigate-outline",
  "Hiking & Trekking": "trail-sign-outline",
  "Skateboarding": "walk-outline",
  "Rock Climbing": "trending-up-outline",
  "Golf": "golf-outline",
  "Pilates": "body-outline",
  "Programming": "code-slash-outline",
  "App Development": "phone-portrait-outline",
  "Web Development": "globe-outline",
  "AI / Machine Learning": "hardware-chip-outline",
  "Cybersecurity": "shield-checkmark-outline",
  "Python": "code-slash-outline",
  "Java": "code-slash-outline",
  "Data Science": "analytics-outline",
  "Cloud Computing": "cloud-outline",
  "Blockchain / Web3": "link-outline",
  "DevOps": "server-outline",
  "3D Printing": "cube-outline",
  "React Native": "phone-portrait-outline",
  "JavaScript / TypeScript": "code-slash-outline",
  "SQL & Databases": "server-outline",
  "Competitive Programming": "trophy-outline",
  "Robotics": "hardware-chip-outline",
  "IoT": "wifi-outline",
  "Game Development": "game-controller-outline",
  "AR / VR": "glasses-outline",
  "Open Source": "git-branch-outline",
  "UI/UX Design": "color-wand-outline",
  "Graphic Design": "color-wand-outline",
  "Motion Design": "film-outline",
  "3D Modeling": "cube-outline",
  "Illustration": "brush-outline",
  "Brand Design": "ribbon-outline",
  "Product Design": "cube-outline",
  "Interior Design": "home-outline",
  "Architecture": "business-outline",
  "Video Editing": "cut-outline",
  "Freelancing": "laptop-outline",
  "Entrepreneurship": "briefcase-outline",
  "Public Speaking": "mic-outline",
  "Networking Events": "people-outline",
  "Finance & Accounting": "calculator-outline",
  "Human Resources": "people-outline",
  "Law": "hammer-outline",
  "Medicine & Healthcare": "medkit-outline",
  "Teaching & Education": "school-outline",
  "Civil Services": "shield-outline",
  "Journalism": "newspaper-outline",
  "Research & Academia": "flask-outline",
  "Supply Chain & Logistics": "cube-outline",
  "Aviation": "airplane-outline",
  "Engineering (Core)": "construct-outline",
  "Reading": "book-outline",
  "Language Learning": "language-outline",
  "Certifications & Courses": "ribbon-outline",
  "Mentoring": "people-outline",
  "Volunteering": "heart-outline",
  "Personal Development": "trending-up-outline",
  "Meditation & Mindfulness": "leaf-outline",
  "Fitness & Wellness": "heart-outline",
  "Minimalism": "leaf-outline",
  "Sustainability": "earth-outline",
  "Home Cooking": "restaurant-outline",
  "Coffee & Tea Culture": "cafe-outline",
};

export const DEFAULT_SKILL_ICON = "flash-outline";