// constants/skillIcons.ts
export const SKILL_ICONS: Record<string, string> = {
  Art: "color-palette-outline",
  Painting: "brush-outline",
  Photography: "camera-outline",
  Videography: "videocam-outline",
  Acting: "happy-outline",
  Singing: "mic-outline",
  Freefire: "game-controller-outline",
  BGMI: "game-controller-outline",
  Freelancing: "laptop-outline",
  Gym: "barbell-outline",
  Yoga: "body-outline",
  Running: "walk-outline",
  Cycling: "bicycle-outline",
  Swimming: "water-outline",
  Boxing: "fitness-outline",
  Bulking: "fitness-outline",
  "Weight Loss": "scale-outline",
  PowerLifter: "barbell-outline",
  Bodybuilding: "body-outline",
  Programming: "code-slash-outline",
  "App Development": "phone-portrait-outline",
  "Web Development": "globe-outline",
  "AI / ML": "hardware-chip-outline",
  Cybersecurity: "shield-checkmark-outline",
  "UI/UX Design": "color-wand-outline",
  Python: "code-slash-outline",
  Java: "code-slash-outline",
  "Govt Prep": "book-outline",
  Business: "briefcase-outline",
  "Short Films": "film-outline",
  Football: "football-outline",
  Cricket: "baseball-outline",
  Basketball: "basketball-outline",
  Tennis: "tennisball-outline",
  Kabaddi: "people-outline",
  Athletics: "timer-outline",
  Startups: "rocket-outline",
  "Content Creator": "create-outline",
  Music: "musical-notes-outline",
  Dancing: "walk-outline",
  Writing: "pencil-outline",
  Sketching: "brush-outline",
  Cooking: "restaurant-outline",
  Travel: "airplane-outline",
  Fashion: "shirt-outline",
  Podcast: "mic-circle-outline",
  Gardening: "leaf-outline",
  "Pets & Animals": "paw-outline",
  Chess: "grid-outline",
  Badminton: "tennisball-outline",
  Volleyball: "football-outline",
  "Table Tennis": "tennisball-outline",
  "Martial Arts": "fitness-outline",
  Calisthenics: "body-outline",
  Archery: "navigate-outline",
  "Data Science": "analytics-outline",
  "Cloud Computing": "cloud-outline",
  Blockchain: "link-outline",
  "React Native": "phone-portrait-outline",
  DevOps: "server-outline",
  "3D Printing": "cube-outline",
  "Graphic Design": "color-wand-outline",
  "Motion Design": "film-outline",
  "3D Modeling": "cube-outline",
  Illustration: "brush-outline",
  "Brand Design": "ribbon-outline",
  Marketing: "megaphone-outline",
  Trading: "swap-horizontal-outline",
  "E-Commerce": "storefront-outline",
  Filmmaking: "videocam-outline",
  "Music Production": "headset-outline",
  Skincare: "sparkles-outline",
};

export const DEFAULT_SKILL_ICON = "flash-outline";