export const SKILL_ICONS: Record<string, string> = {
  "Art": "color-palette-outline",
  "Painting": "brush-outline",
  "Photography": "camera-outline",
  "Videography": "videocam-outline",
  "Acting": "film-outline",
  "Singing": "mic-outline",
  "Govt Exam Prep": "book-outline",
  "Short Films": "film-outline",
  "Content Creation": "create-outline",
  "Music": "musical-notes-outline",
  "Dancing": "body-outline",
  "Writing": "pencil-outline",
  "Sketching": "brush-outline",
  "Cooking": "restaurant-outline",
  "Travel": "airplane-outline",
  "Fashion & Styling": "shirt-outline",
  "Podcasting": "mic-circle-outline",
  "Filmmaking": "videocam-outline",
  "Music Production": "headset-outline",
  "Skincare & Beauty": "sparkles-outline",
  "Poetry": "quill-outline",
  "Theatre": "megaphone-outline",
  "Instrument Playing": "musical-notes-outline",
  "Free Fire": "game-controller-outline",
  "BGMI": "game-controller-outline",
  "Chess": "grid-outline",
  "PC/Console Gaming": "game-controller-outline",
  "Board Games": "grid-outline",
  "Gym & Weight Training": "barbell-outline",
  "Yoga": "body-outline",
  "Running": "walk-outline",
  "Cycling": "bicycle-outline",
  "Swimming": "water-outline",
  "Boxing": "fitness-outline",
  "Powerlifting": "barbell-outline",
  "Bodybuilding": "body-outline",
  "Football": "football-outline",
  "Cricket": "baseball-outline",
  "Basketball": "basketball-outline",
  "Tennis": "tennisball-outline",
  "Kabaddi": "people-outline",
  "Athletics": "timer-outline",
  "Badminton": "tennisball-outline",
  "Volleyball": "football-outline",
  "Table Tennis": "tennisball-outline",
  "Martial Arts": "fitness-outline",
  "Calisthenics": "body-outline",
  "Archery": "navigate-outline",
  "Skateboarding": "walk-outline",
  "Programming": "code-slash-outline",
  "App Development": "phone-portrait-outline",
  "Web Development": "globe-outline",
  "AI / Machine Learning": "hardware-chip-outline",
  "Cybersecurity": "shield-checkmark-outline",
  "Python": "code-slash-outline",
  "Java": "code-slash-outline",
  "Data Science": "analytics-outline",
  "Cloud Computing": "cloud-outline",
  "3D Printing": "cube-outline",
  "React Native": "phone-portrait-outline",
  "JavaScript / TypeScript": "code-slash-outline",
  "SQL & Databases": "server-outline",
  "Robotics": "hardware-chip-outline",
  "IoT": "wifi-outline",
  "Game Development": "game-controller-outline",
  "UI/UX Design": "color-wand-outline",
  "Graphic Design": "color-wand-outline",
  "Motion Design": "film-outline",
  "3D Modeling": "cube-outline",
  "Illustration": "brush-outline",
  "Brand Design": "ribbon-outline",
  "Product Design": "cube-outline",
  "Architecture": "business-outline",
  "Video Editing": "cut-outline",
  "Freelancing": "laptop-outline",
  "Public Speaking": "mic-outline",
  "Human Resources": "people-outline",
  "Law": "hammer-outline",
  "Teaching & Education": "school-outline",
  "Civil Services": "shield-outline",
  "Books Reading": "book-outline",
  "English Communication": "language-outline",
  "Fitness": "heart-outline",
};

export const DEFAULT_SKILL_ICON = "flash-outline";